spring:
  application:
    name:
      Spring-Security-Kt
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_kt
    username: postgres
    password: 1204
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
